/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dosindchuc.UI.swing;


import dosindchuc.UI.controller.ManagementSearchActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ir
 */
public class ManagementFrm extends javax.swing.JFrame {

    ManagementSearchActionListener listeners;
    
    
    /**
     * Creates new form ManagementFrm
     */
    public ManagementFrm() {
        initComponents();
        
        listeners = new ManagementSearchActionListener(this);
//        setSettingsSearchTable ();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelWorkerInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtWorkerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWorkerBI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtWorkerNick = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtWorkerMec = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtWorkerNIF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtWorkerNationality = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtWorkerBirthYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWorkerBirthMonth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtWorkerBirthDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbWorkerSex = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cbWorkerCat = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbWorkerDept = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtWorkerSector = new javax.swing.JTextField();
        tbPanelWorker = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtWorkerComments = new javax.swing.JTextArea();
        btWorkerNew = new javax.swing.JButton();
        btWorkerSave = new javax.swing.JButton();
        btWorkerCancel = new javax.swing.JButton();
        txtWorkerCreateTimeStamp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btWorkerUpdate = new javax.swing.JButton();
        cbWorkerStatus = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDosimeterInfo = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDosimeterNote = new javax.swing.JTextArea();
        btDosimeterInfoNew = new javax.swing.JButton();
        btDosimeterInfoSave = new javax.swing.JButton();
        btDosimeterInfoCancel = new javax.swing.JButton();
        btDosimeterInfoUpdate = new javax.swing.JButton();
        cbDosimeterNotesIndex = new javax.swing.JComboBox();
        cbDosimeterNotesAlert = new javax.swing.JComboBox();
        cbDosimeterNotesStatus = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        txtDosimeterNotesDateCreated = new javax.swing.JTextField();
        txtDosimeterNoteAlertdate = new javax.swing.JTextField();
        txtDosimeterNoteStatusDate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDoseInfo = new javax.swing.JTable();
        btDoseNew = new javax.swing.JButton();
        btDoseSave = new javax.swing.JButton();
        btDoseCancel = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDoseNote = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        cbDoseNoteLevel = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cbDoseNoteStatus = new javax.swing.JComboBox();
        txtDoseNoteLevelDate = new javax.swing.JTextField();
        txtDoseNoteStatusDate = new javax.swing.JTextField();
        btDoseUpdate = new javax.swing.JButton();
        cbDoseNoteIndex = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtDoseNotesDateCreated = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        panelSearch = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        searchWorkerName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        searchCBCategory = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        searchCBdepartment = new javax.swing.JComboBox();
        searchBtSeach = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        searchTxtMec = new javax.swing.JTextField();
        searchBtClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/couple48.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        jButton2.setVerifyInputWhenFocusTarget(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logotipo_chuc_novo_48.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelWorkerInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelWorkerInfo.setEnabled(false);
        panelWorkerInfo.setFocusable(false);
        panelWorkerInfo.setRequestFocusEnabled(false);
        panelWorkerInfo.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Name:");

        jLabel2.setText("BI:");

        jLabel3.setText("Nick:");

        jLabel4.setText("Mec.");

        jLabel5.setText("NIF:");

        jLabel6.setText("Nacionality:");

        jLabel7.setText("Birth:");

        jLabel8.setText("/");

        jLabel9.setText("/");

        jLabel10.setText("Sex:");

        cbWorkerSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));

        jLabel11.setText("Category:");

        cbWorkerCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Médico", "Físico", "Técnico", "Secretário", "Enfermeiro", "Auxiliar", "NoDef" }));

        jLabel12.setText("Department:");

        cbWorkerDept.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cbWorkerDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RT", "Img", "Orto", "BOC", "MN", "NoDef" }));

        jLabel13.setText("Sector:");

        jLabel14.setText("Comments:");

        txtWorkerComments.setColumns(20);
        txtWorkerComments.setLineWrap(true);
        txtWorkerComments.setRows(5);
        jScrollPane1.setViewportView(txtWorkerComments);

        btWorkerNew.setText("New");

        btWorkerSave.setText("Save");

        btWorkerCancel.setText("Cancel");

        txtWorkerCreateTimeStamp.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        jLabel23.setText("Dosimeter in use:");

        jLabel24.setText("Total dose (year):");

        btWorkerUpdate.setText("Update");

        cbWorkerStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btWorkerNew)
                                .addGap(58, 58, 58)
                                .addComponent(btWorkerUpdate)
                                .addGap(171, 171, 171)
                                .addComponent(btWorkerSave))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbWorkerStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btWorkerCancel)
                            .addComponent(txtWorkerCreateTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkerCreateTimeStamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(cbWorkerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btWorkerNew)
                    .addComponent(btWorkerSave)
                    .addComponent(btWorkerCancel)
                    .addComponent(btWorkerUpdate))
                .addGap(45, 45, 45))
        );

        tbPanelWorker.addTab("More Info", jPanel3);

        tableDosimeterInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tableDosimeterInfo);

        jLabel18.setText("Note:");

        txtDosimeterNote.setColumns(20);
        txtDosimeterNote.setRows(5);
        jScrollPane5.setViewportView(txtDosimeterNote);

        btDosimeterInfoNew.setText("New");

        btDosimeterInfoSave.setText("Save");

        btDosimeterInfoCancel.setText("Cancel");

        btDosimeterInfoUpdate.setText("Update");

        cbDosimeterNotesAlert.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PI", "N", "I", "MI", "C" }));
        cbDosimeterNotesAlert.setActionCommand("cbDosimeterNotesAlert");

        cbDosimeterNotesStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "C" }));
        cbDosimeterNotesStatus.setActionCommand("cbDosimeterNotesStatus");

        jLabel27.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel27.setText("Created @");

        txtDosimeterNotesDateCreated.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtDosimeterNotesDateCreated.setBorder(null);

        txtDosimeterNoteAlertdate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        txtDosimeterNoteStatusDate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btDosimeterInfoNew)
                .addGap(35, 35, 35)
                .addComponent(btDosimeterInfoUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDosimeterInfoSave)
                .addGap(40, 40, 40)
                .addComponent(btDosimeterInfoCancel)
                .addGap(73, 73, 73))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbDosimeterNotesIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDosimeterNotesDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDosimeterNotesAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDosimeterNotesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDosimeterNoteStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDosimeterNoteAlertdate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDosimeterNotesIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtDosimeterNotesDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDosimeterNotesAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDosimeterNoteAlertdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDosimeterNotesStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDosimeterNoteStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(78, 78, 78)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDosimeterInfoNew)
                            .addComponent(btDosimeterInfoSave)
                            .addComponent(btDosimeterInfoCancel)
                            .addComponent(btDosimeterInfoUpdate))
                        .addGap(57, 57, 57))))
        );

        tbPanelWorker.addTab("Dosimeter Info", jPanel5);

        tableDoseInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableDoseInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableDoseInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableDoseInfo);

        btDoseNew.setText("New");

        btDoseSave.setText("Save");

        btDoseCancel.setText("Cancel");

        jLabel15.setText("Note:");

        txtDoseNote.setColumns(20);
        txtDoseNote.setRows(5);
        jScrollPane3.setViewportView(txtDoseNote);

        jLabel16.setText("Level:");

        cbDoseNoteLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PI", "N", "I", "MI", "C" }));

        jLabel17.setText("Status:");

        cbDoseNoteStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "C" }));

        txtDoseNoteLevelDate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        txtDoseNoteStatusDate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        btDoseUpdate.setText("Update");

        cbDoseNoteIndex.setActionCommand("cbDoseNoteIndex");

        jLabel25.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel25.setText("Timestamp");

        jLabel26.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel26.setText("Created @");

        txtDoseNotesDateCreated.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtDoseNotesDateCreated.setBorder(null);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(cbDoseNoteIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btDoseNew)
                                .addGap(44, 44, 44)
                                .addComponent(btDoseUpdate)
                                .addGap(224, 224, 224)
                                .addComponent(btDoseSave)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDoseNoteLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDoseNoteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDoseNoteLevelDate, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txtDoseNoteStatusDate))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(btDoseCancel)
                                .addGap(79, 79, 79))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDoseNotesDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(59, 59, 59))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtDoseNotesDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(cbDoseNoteIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(cbDoseNoteLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDoseNoteLevelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbDoseNoteStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoseNoteStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDoseNew)
                    .addComponent(btDoseSave)
                    .addComponent(btDoseCancel)
                    .addComponent(btDoseUpdate))
                .addGap(49, 49, 49))
        );

        tbPanelWorker.addTab("Dose Info", jPanel4);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelWorkerInfoLayout = new javax.swing.GroupLayout(panelWorkerInfo);
        panelWorkerInfo.setLayout(panelWorkerInfoLayout);
        panelWorkerInfoLayout.setHorizontalGroup(
            panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWorkerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbPanelWorker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWorkerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWorkerBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtWorkerBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWorkerBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWorkerBI, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWorkerNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(txtWorkerNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWorkerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(txtWorkerNick, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWorkerMec, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWorkerInfoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWorkerSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWorkerCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbWorkerDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWorkerSector, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addGap(27, 27, 27))
        );
        panelWorkerInfoLayout.setVerticalGroup(
            panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWorkerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtWorkerNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtWorkerMec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWorkerBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtWorkerNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtWorkerNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtWorkerBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtWorkerBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtWorkerBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelWorkerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbWorkerSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cbWorkerCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbWorkerDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtWorkerSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbPanelWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel19.setText("Name:");

        jLabel20.setText("Department:");

        searchCBCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Médico", "Físico", "Técnico", "Secretário", "Enfermeiro", "Auxiliar", "NoDef" }));
        searchCBCategory.setSelectedIndex(6);
        searchCBCategory.setToolTipText("");

        jLabel21.setText("Category:");

        searchCBdepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RT", "Img", "Orto", "BOC", "MN", "NoDef" }));
        searchCBdepartment.setSelectedIndex(5);

        searchBtSeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search48.png"))); // NOI18N
        searchBtSeach.setActionCommand("searchManagement");
        searchBtSeach.setBorderPainted(false);
        searchBtSeach.setContentAreaFilled(false);
        searchBtSeach.setFocusPainted(false);

        searchTable.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        searchTable.setRequestFocusEnabled(false);
        searchTable.getTableHeader().setReorderingAllowed(false);
        searchTable.setUpdateSelectionOnSort(false);
        searchTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane6.setViewportView(searchTable);
        searchTable.getAccessibleContext().setAccessibleName("tableSearch");

        jLabel22.setText("Nº Mec:");

        searchBtClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear48.png"))); // NOI18N
        searchBtClean.setActionCommand("cleanManagement");
        searchBtClean.setBorderPainted(false);
        searchBtClean.setContentAreaFilled(false);

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSearchLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchTxtMec, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSearchLayout.createSequentialGroup()
                                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelSearchLayout.createSequentialGroup()
                                        .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(searchWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelSearchLayout.createSequentialGroup()
                                                .addComponent(searchCBdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(searchBtSeach))))
                                    .addGroup(panelSearchLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(searchCBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchBtClean))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6)))
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(searchWorkerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                        .addComponent(searchBtClean)
                        .addGap(27, 27, 27))
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSearchLayout.createSequentialGroup()
                                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(searchCBdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchCBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)))
                            .addComponent(searchBtSeach))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(searchTxtMec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWorkerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelWorkerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("1Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManagementFrm().setVisible(true);
//            }
//        });
    }
    
    
    
       
//     searchTable
    
    
    
    public DefaultTableModel setSettingsSearchTable () {
 
        
        DefaultTableModel model = new DefaultTableModel(new Object [][] {},
                new String [] { "Mec", "Name", "Category", "Department", "Status" }
                ){
                    @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                            return false; //Disallow the editing of any cell
                    }
                };
        
        searchTable.setModel(model);
        
        searchTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        searchTable.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        searchTable.setFocusable(true);
        searchTable.setRequestFocusEnabled(true);
        searchTable.setUpdateSelectionOnSort(false);
        searchTable.setDragEnabled(false);
        searchTable.setRowSelectionAllowed(true);
         
        searchTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        searchTable.getColumnModel().getColumn(1).setPreferredWidth(210);
        searchTable.getColumnModel().getColumn(2).setPreferredWidth(90);
        searchTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        searchTable.getColumnModel().getColumn(4).setPreferredWidth(70);
        
        return model;
        
    }
    
    
    public DefaultTableModel setSettingsDoseTable () {
 
        
        DefaultTableModel model = new DefaultTableModel(new Object [][] {},
                new String [] { "Year", "Trimester", "Month", "Hp007", "Hp10", "Comments", "LastChange" }
                ){
                    @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                            return false; //Disallow the editing of any cell
                    }
                };
        
        tableDoseInfo.setModel(model);
        
        tableDoseInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableDoseInfo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        tableDoseInfo.setFocusable(true);
        tableDoseInfo.setRequestFocusEnabled(true);
        tableDoseInfo.setUpdateSelectionOnSort(false);
        tableDoseInfo.setDragEnabled(false);
        tableDoseInfo.setRowSelectionAllowed(true);
         
        tableDoseInfo.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableDoseInfo.getColumnModel().getColumn(1).setPreferredWidth(20);
        tableDoseInfo.getColumnModel().getColumn(2).setPreferredWidth(20);
        tableDoseInfo.getColumnModel().getColumn(3).setPreferredWidth(20);
        tableDoseInfo.getColumnModel().getColumn(4).setPreferredWidth(100);
        tableDoseInfo.getColumnModel().getColumn(5).setPreferredWidth(90);
        
        return model;
        
    }
    
    
    public DefaultTableModel setSettingsDosimeterTable () {
 
        
        DefaultTableModel model = new DefaultTableModel(new Object [][] {},
                new String [] { "Id", "Label", "Type", "Periodicity", "Supplier", "Status", "LastChange" }
                ){
                    @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                            return false; //Disallow the editing of any cell
                    }
                };
        
        tableDosimeterInfo.setModel(model);
        
        tableDosimeterInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableDosimeterInfo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        tableDosimeterInfo.setFocusable(true);
        tableDosimeterInfo.setRequestFocusEnabled(true);
        tableDosimeterInfo.setUpdateSelectionOnSort(false);
        tableDosimeterInfo.setDragEnabled(false);
        tableDosimeterInfo.setRowSelectionAllowed(true);
         
        tableDosimeterInfo.getColumnModel().getColumn(0).setPreferredWidth(20);
        tableDosimeterInfo.getColumnModel().getColumn(1).setPreferredWidth(20);
        tableDosimeterInfo.getColumnModel().getColumn(2).setPreferredWidth(20);
        tableDosimeterInfo.getColumnModel().getColumn(3).setPreferredWidth(20);
        tableDosimeterInfo.getColumnModel().getColumn(4).setPreferredWidth(20);
        tableDosimeterInfo.getColumnModel().getColumn(5).setPreferredWidth(110);
        tableDosimeterInfo.getColumnModel().getColumn(5).setPreferredWidth(90);
        
        return model;
        
    }
    
    
    // getter and setters 

    public JComboBox getSearchCBCategory() {
        return searchCBCategory;
    }

    public void setSearchCBCategory(JComboBox searchCBCategory) {
        this.searchCBCategory = searchCBCategory;
    }

    public JComboBox getSearchCBdepartment() {
        return searchCBdepartment;
    }

    public void setSearchCBdepartment(JComboBox searchCBdepartment) {
        this.searchCBdepartment = searchCBdepartment;
    }

    public JTextField getSearchTxtMec() {
        return searchTxtMec;
    }

    public void setSearchTxtMec(JTextField searchTxtMec) {
        this.searchTxtMec = searchTxtMec;
    }

    public JTextField getSearchWorkerName() {
        return searchWorkerName;
    }

    public void setSearchWorkerName(JTextField searchWorkerName) {
        this.searchWorkerName = searchWorkerName;
    }

    public JButton getSearchBtSeach() {
        return searchBtSeach;
    }

    public void setSearchBtSeach(JButton searchBtSeach) {
        this.searchBtSeach = searchBtSeach;
    }

    public JButton getSearchBtClean() {
        return searchBtClean;
    }

    public void setSearchBtClean(JButton searchBtClean) {
        this.searchBtClean = searchBtClean;
    }

    public JTable getSearchTable() {
        return searchTable;
    }

    public void setSearchTable(JTable searchTable) {
        this.searchTable = searchTable;
    }

    public JButton getBtWorkerNew() {
        return btWorkerNew;
    }

    public void setBtWorkerNew(JButton btWorkerNew) {
        this.btWorkerNew = btWorkerNew;
    }

    public JButton getBtWorkerSave() {
        return btWorkerSave;
    }

    public void setBtWorkerSave(JButton btWorkerSave) {
        this.btWorkerSave = btWorkerSave;
    }

    public JButton getBtWorkerUpdate() {
        return btWorkerUpdate;
    }

    public void setBtWorkerUpdate(JButton btWorkerUpdate) {
        this.btWorkerUpdate = btWorkerUpdate;
    }

    public JComboBox getCbWorkerCat() {
        return cbWorkerCat;
    }

    public void setCbWorkerCat(JComboBox cbWorkerCat) {
        this.cbWorkerCat = cbWorkerCat;
    }

    public JComboBox getCbWorkerDept() {
        return cbWorkerDept;
    }

    public void setCbWorkerDept(JComboBox cbWorkerDept) {
        this.cbWorkerDept = cbWorkerDept;
    }

    public JComboBox getCbWorkerSex() {
        return cbWorkerSex;
    }

    public void setCbWorkerSex(JComboBox cbWorkerSex) {
        this.cbWorkerSex = cbWorkerSex;
    }

    public JTabbedPane getTbPanelWorker() {
        return tbPanelWorker;
    }

    public void setTbPanelWorker(JTabbedPane tbPanelWorker) {
        this.tbPanelWorker = tbPanelWorker;
    }

    public JTextField getTxtWorkerBI() {
        return txtWorkerBI;
    }

    public void setTxtWorkerBI(JTextField txtWorkerBI) {
        this.txtWorkerBI = txtWorkerBI;
    }

    public JTextField getTxtWorkerBirthDay() {
        return txtWorkerBirthDay;
    }

    public void setTxtWorkerBirthDay(JTextField txtWorkerBirthDay) {
        this.txtWorkerBirthDay = txtWorkerBirthDay;
    }

    public JTextField getTxtWorkerBirthMonth() {
        return txtWorkerBirthMonth;
    }

    public void setTxtWorkerBirthMonth(JTextField txtWorkerBirthMonth) {
        this.txtWorkerBirthMonth = txtWorkerBirthMonth;
    }

    public JTextField getTxtWorkerBirthYear() {
        return txtWorkerBirthYear;
    }

    public void setTxtWorkerBirthYear(JTextField txtWorkerBirthYear) {
        this.txtWorkerBirthYear = txtWorkerBirthYear;
    }

    public JTextArea getTxtWorkerComments() {
        return txtWorkerComments;
    }

    public void setTxtWorkerComments(JTextArea txtWorkerComments) {
        this.txtWorkerComments = txtWorkerComments;
    }

    public JTextField getTxtWorkerMec() {
        return txtWorkerMec;
    }

    public void setTxtWorkerMec(JTextField txtWorkerMec) {
        this.txtWorkerMec = txtWorkerMec;
    }

    public JTextField getTxtWorkerNIF() {
        return txtWorkerNIF;
    }

    public void setTxtWorkerNIF(JTextField txtWorkerNIF) {
        this.txtWorkerNIF = txtWorkerNIF;
    }

    public JTextField getTxtWorkerName() {
        return txtWorkerName;
    }

    public void setTxtWorkerName(JTextField txtWorkerName) {
        this.txtWorkerName = txtWorkerName;
    }

    public JTextField getTxtWorkerNationality() {
        return txtWorkerNationality;
    }

    public void setTxtWorkerNationality(JTextField txtWorkerNationality) {
        this.txtWorkerNationality = txtWorkerNationality;
    }

    public JTextField getTxtWorkerNick() {
        return txtWorkerNick;
    }

    public void setTxtWorkerNick(JTextField txtWorkerNick) {
        this.txtWorkerNick = txtWorkerNick;
    }

    public JTextField getTxtWorkerSector() {
        return txtWorkerSector;
    }

    public void setTxtWorkerSector(JTextField txtWorkerSector) {
        this.txtWorkerSector = txtWorkerSector;
    }

    public JComboBox getCbWorkerStatus() {
        return cbWorkerStatus;
    }

    public void setCbWorkerStatus(JComboBox cbWorkerStatus) {
        this.cbWorkerStatus = cbWorkerStatus;
    }

    public JTextField getTxtWorkerCreateTimeStamp() {
        return txtWorkerCreateTimeStamp;
    }

    public void setTxtWorkerCreateTimeStamp(JTextField txtWorkerCreateTimeStamp) {
        this.txtWorkerCreateTimeStamp = txtWorkerCreateTimeStamp;
    }

    public JComboBox getCbDoseNoteLevel() {
        return cbDoseNoteLevel;
    }

    public void setCbDoseNoteLevel(JComboBox cbDoseNoteLevel) {
        this.cbDoseNoteLevel = cbDoseNoteLevel;
    }

    public JComboBox getCbDoseNoteStatus() {
        return cbDoseNoteStatus;
    }

    public void setCbDoseNoteStatus(JComboBox cbDoseNoteStatus) {
        this.cbDoseNoteStatus = cbDoseNoteStatus;
    }

    public JTextArea getTxtDoseNote() {
        return txtDoseNote;
    }

    public void setTxtDoseNote(JTextArea txtDoseNote) {
        this.txtDoseNote = txtDoseNote;
    }

    public JTextField getTxtDoseNoteLevelDate() {
        return txtDoseNoteLevelDate;
    }

    public void setTxtDoseNoteLevelDate(JTextField txtDoseNoteLevelDate) {
        this.txtDoseNoteLevelDate = txtDoseNoteLevelDate;
    }

    public JTextField getTxtDoseNoteStatusDate() {
        return txtDoseNoteStatusDate;
    }

    public void setTxtDoseNoteStatusDate(JTextField txtDoseNoteStatusDate) {
        this.txtDoseNoteStatusDate = txtDoseNoteStatusDate;
    }

    public JComboBox getCbDoseNoteIndex() {
        return cbDoseNoteIndex;
    }

    public void setCbDoseNoteIndex(JComboBox cbDoseNoteIndex) {
        this.cbDoseNoteIndex = cbDoseNoteIndex;
    }

    public JTextField getTxtDoseNotesDateCreated() {
        return txtDoseNotesDateCreated;
    }

    public void setTxtDoseNotesDateCreated(JTextField txtDoseNotesDateCreated) {
        this.txtDoseNotesDateCreated = txtDoseNotesDateCreated;
    }

    public JComboBox getCbDosimeterNotesAlert() {
        return cbDosimeterNotesAlert;
    }

    public void setCbDosimeterNotesAlert(JComboBox cbDosimeterNotesAlert) {
        this.cbDosimeterNotesAlert = cbDosimeterNotesAlert;
    }

    public JComboBox getCbDosimeterNotesIndex() {
        return cbDosimeterNotesIndex;
    }

    public void setCbDosimeterNotesIndex(JComboBox cbDosimeterNotesIndex) {
        this.cbDosimeterNotesIndex = cbDosimeterNotesIndex;
    }

    public JComboBox getCbDosimeterNotesStatus() {
        return cbDosimeterNotesStatus;
    }

    public void setCbDosimeterNotesStatus(JComboBox cbDosimeterNotesStatus) {
        this.cbDosimeterNotesStatus = cbDosimeterNotesStatus;
    }

    public JTextArea getTxtDosimeterNote() {
        return txtDosimeterNote;
    }

    public void setTxtDosimeterNote(JTextArea txtDosimeterNote) {
        this.txtDosimeterNote = txtDosimeterNote;
    }

    public JTextField getTxtDosimeterNoteAlertdate() {
        return txtDosimeterNoteAlertdate;
    }

    public void setTxtDosimeterNoteAlertdate(JTextField txtDosimeterNoteAlertdate) {
        this.txtDosimeterNoteAlertdate = txtDosimeterNoteAlertdate;
    }

    public JTextField getTxtDosimeterNoteStatusDate() {
        return txtDosimeterNoteStatusDate;
    }

    public void setTxtDosimeterNoteStatusDate(JTextField txtDosimeterNoteStatusDate) {
        this.txtDosimeterNoteStatusDate = txtDosimeterNoteStatusDate;
    }

    public JTextField getTxtDosimeterNotesDateCreated() {
        return txtDosimeterNotesDateCreated;
    }

    public void setTxtDosimeterNotesDateCreated(JTextField txtDosimeterNotesDateCreated) {
        this.txtDosimeterNotesDateCreated = txtDosimeterNotesDateCreated;
    }

    
    
    

 
    
    
   
    
    
//    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDoseCancel;
    private javax.swing.JButton btDoseNew;
    private javax.swing.JButton btDoseSave;
    private javax.swing.JButton btDoseUpdate;
    private javax.swing.JButton btDosimeterInfoCancel;
    private javax.swing.JButton btDosimeterInfoNew;
    private javax.swing.JButton btDosimeterInfoSave;
    private javax.swing.JButton btDosimeterInfoUpdate;
    private javax.swing.JButton btWorkerCancel;
    private javax.swing.JButton btWorkerNew;
    private javax.swing.JButton btWorkerSave;
    private javax.swing.JButton btWorkerUpdate;
    public javax.swing.JComboBox cbDoseNoteIndex;
    private javax.swing.JComboBox cbDoseNoteLevel;
    private javax.swing.JComboBox cbDoseNoteStatus;
    public javax.swing.JComboBox cbDosimeterNotesAlert;
    public javax.swing.JComboBox cbDosimeterNotesIndex;
    public javax.swing.JComboBox cbDosimeterNotesStatus;
    private javax.swing.JComboBox cbWorkerCat;
    private javax.swing.JComboBox cbWorkerDept;
    private javax.swing.JComboBox cbWorkerSex;
    private javax.swing.JComboBox cbWorkerStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelSearch;
    public javax.swing.JPanel panelWorkerInfo;
    public javax.swing.JButton searchBtClean;
    public javax.swing.JButton searchBtSeach;
    private javax.swing.JComboBox searchCBCategory;
    private javax.swing.JComboBox searchCBdepartment;
    public javax.swing.JTable searchTable;
    private javax.swing.JTextField searchTxtMec;
    private javax.swing.JTextField searchWorkerName;
    public javax.swing.JTable tableDoseInfo;
    public javax.swing.JTable tableDosimeterInfo;
    private javax.swing.JTabbedPane tbPanelWorker;
    private javax.swing.JTextArea txtDoseNote;
    private javax.swing.JTextField txtDoseNoteLevelDate;
    private javax.swing.JTextField txtDoseNoteStatusDate;
    public javax.swing.JTextField txtDoseNotesDateCreated;
    public javax.swing.JTextArea txtDosimeterNote;
    public javax.swing.JTextField txtDosimeterNoteAlertdate;
    public javax.swing.JTextField txtDosimeterNoteStatusDate;
    public javax.swing.JTextField txtDosimeterNotesDateCreated;
    private javax.swing.JTextField txtWorkerBI;
    private javax.swing.JTextField txtWorkerBirthDay;
    private javax.swing.JTextField txtWorkerBirthMonth;
    private javax.swing.JTextField txtWorkerBirthYear;
    private javax.swing.JTextArea txtWorkerComments;
    private javax.swing.JTextField txtWorkerCreateTimeStamp;
    private javax.swing.JTextField txtWorkerMec;
    private javax.swing.JTextField txtWorkerNIF;
    private javax.swing.JTextField txtWorkerName;
    private javax.swing.JTextField txtWorkerNationality;
    private javax.swing.JTextField txtWorkerNick;
    private javax.swing.JTextField txtWorkerSector;
    // End of variables declaration//GEN-END:variables
}
